### PR TITLE
Fix cleanup warnings in `tests/minimal.rs` when compiled for windows.

### LINKED ISSUE #21: cleanup warnings in `tests/minimal.rs` when compiled for windows.
some cfg juggling just needs to be done, should be quite simple

### PR DESCRIPTION
**Pull request by IamSaquib**
Fixes #21

### CODE REVIEW

File: tests/minimal.rs [hunk 1]
```diff
@@ -52,8 +69,16 @@ fn read_config() -> Result<(), Report> {
...
+
+#[cfg(windows)]
+#[cfg(feature = "capture-spantrace")]
+static WINDOWS_EXPECTED: &str = "Error: \n   0: \u{1b}[38;5;9mUnable to read config\u{1b}[0m\n   1: \u{1b}[38;5;9mThe system cannot find the file specified. (os error 2)\u{1b}[0m\n\n  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n  \n   0: \u{1b}[38;5;9mminimal\u{1b}[0m\u{1b}[38;5;9m::\u{1b}[0m\u{1b}[38;5;9mread_file\u{1b}[0m with \u{1b}[38;5;14mpath=\"fake_file\"\u{1b}[0m\n      at tests\\minimal.rs:58\n   1: \u{1b}[38;5;9mminimal\u{1b}[0m\u{1b}[38;5;9m::\u{1b}[0m\u{1b}[38;5;9mread_config\u{1b}[0m\n      at tests\\minimal.rs:64\n\n\u{1b}[38;5;14mSuggestion\u{1b}[0m: try using a file that exists next time";
+
+#[cfg(not(feature = "capture-spantrace"))]
+static WINDOWS_EXPECTED: &str = "Error: \n   0: \u{1b}[38;5;9mUnable to read config\u{1b}[0m\n   1: \u{1b}[38;5;9mThe system cannot find the file specified. (os error 2)\u{1b}[0m\n\n\u{1b}[38;5;14mSuggestion\u{1b}[0m: try using a file that exists next time";
```
Comment (yaahc) [inline tests/minimal.rs:84]: Looks like this one needs to have `#[cfg(windows)]` added as well
