### PR TITLE
fix: Do not panic on multiple `install` calls

### LINKED ISSUE #97: install call panics instead of returning a result
Currently colored_eyre panics [here](https://github.com/yaahc/color-eyre/blob/07b9f0351544e2b07fcd173dc1fc602a7fc8bb6b/src/config.rs#L736) if you try to install it multiple times. Thus `let _ = color_eyre::install();` won't work when used in tests and the result from install() is kinda meaningless.

<details>
  <summary>panic backtrace</summary>

```text
0: std::panicking::begin_panic_handler
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\result.rs:1617
   3: core::result::Result::expect<tuple$<>,color_spantrace::InstallThemeError>
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\result.rs:1259
   4: color_eyre::config::HookBuilder::into_hooks
             at C:\Users\Aron\.cargo\registry\src\github.com-1ecc6299db9ec823\color-eyre-0.5.11\src\config.rs:736
   5: color_eyre::config::HookBuilder::install
             at C:\Users\Aron\.cargo\registry\src\github.com-1ecc6299db9ec823\color-eyre-0.5.11\src\config.rs:685
   6: color_eyre::install
             at C:\Users\Aron\.cargo\registry\src\github.com-1ecc6299db9ec823\color-eyre-0.5.11\src\lib.rs:459
```

</details>

### PR DESCRIPTION
**Pull request by jaysonsantos**
When writing tests it is really useful to use color-eyre to have better messages but, calling install multiple times will panic.
This should return an error instead.
It should fix #97

### CODE REVIEW

**Comment by jaysonsantos** [comment]
I wonder if it would be better to use sync::Once on color_eyre::install to make sure only one instance is being installed using a singleton, what do you think? let me know and i can change the pr

**Comment by yaahc** [comment]
I think I prefer this version as is over doing it in a `Once`. It's easy enough[^1] to write a wrapping function using a `Once` if you're going to intentionally race a bunch of installs, and in my experience color-eyre isn't the only library where you need to worry about initializing it once in tests so leaving that to the user seems like the right balance to me.

[^1]: https://github.com/ZcashFoundation/zebra/blob/main/zebra-test/src/lib.rs#L62-L143

**Comment by jaysonsantos** [comment]
@yaahc cool! Then, I just sent the fix for the example as I only ran a simple `cargo test` here

File: src/config.rs [hunk 1]
```diff
@@ -714,7 +715,7 @@ impl HookBuilder {
 
     /// Create a `PanicHook` and `EyreHook` from this `HookBuilder`.
     /// This can be used if you want to combine these handlers with other handlers.
-    pub fn into_hooks(self) -> (PanicHook, EyreHook) {
+    pub fn into_hooks(self) -> Result<(PanicHook, EyreHook), crate::eyre::Report> {
```
Comment (yaahc) [inline src/config.rs:718]: I wasn't paying attention and didn't realize this was introducing a breaking change. I'd prefer to avoid a major version bump, can we rename this to `try_into_hooks` and re-add `into_hooks` with the original signature and panic behavior?

Comment (jaysonsantos) [reply src/config.rs:718]: sure thing

File: src/config.rs [hunk 2]
```diff
@@ -715,6 +716,12 @@ impl HookBuilder {
     /// Create a `PanicHook` and `EyreHook` from this `HookBuilder`.
     /// This can be used if you want to combine these handlers with other handlers.
     pub fn into_hooks(self) -> (PanicHook, EyreHook) {
+        self.try_into_hooks().expect("failed to turn into hooks")
```
Comment (yaahc) [inline src/config.rs:719]:
```suggestion
        self.try_into_hooks().expect("into_hooks should only be called when no `color_spantrace` themes have previously been set")
```

**Comment by yaahc** [comment]
I updated an error message and I think it's gonna break fmt :X

**Comment by jaysonsantos** [comment]
this also seems to fix #78
